"""Number-conserving SO(2) Givens primitive (Eq 29).

The Givens rotation is the one-parameter group generated by
``a_p^dag a_r - a_r^dag a_p``:

    G_{pr}(theta) = exp(theta * (a_p^dag a_r - a_r^dag a_p))

On the one-electron (``N = 1``) subspace with basis ``|e_p> = a_p^dag|vac>``,

    G_{pr}(theta) |e_p> = cos(theta) |e_p> - sin(theta) |e_r>
    G_{pr}(theta) |e_r> = sin(theta) |e_p> + cos(theta) |e_r>

We expose two forms:

* ``givens_fermionic_matrix(theta, p, r, n_qubits)`` -- the full
  ``2**n x 2**n`` dense matrix via JW. This handles arbitrary
  (possibly non-adjacent) ``(p, r)`` and is what all tests use as the
  ground-truth single-gate action.
* ``givens_two_qubit_matrix(theta)`` -- the 4x4 matrix for
  *adjacent* qubits ``(p, r)`` with ``p < r`` and no JW string
  between them. Useful when composing circuits on adjacent qubits.

For the compile-once topology hash (ASSUMPTION #13) we label a
fermionic Givens gate with ``kind = f"Givens({p},{r})"`` and
``qubits = (p, r)``; only ``theta`` changes across masks.
"""
from __future__ import annotations

import numpy as np
from scipy.linalg import expm

from ..circuits.gate import Gate
from ..utils import fermion as jw

__all__ = [
    "givens_fermionic_matrix",
    "givens_two_qubit_matrix",
    "givens_gate",
]


def givens_fermionic_matrix(theta: float, p: int, r: int, n_qubits: int) -> np.ndarray:
    """Full 2**n x 2**n matrix of exp(theta (a_p^dag a_r - a_r^dag a_p))."""
    if p == r:
        raise ValueError("p and r must be distinct")
    adag_p = jw.jw_a_dagger(p, n_qubits)
    a_p = jw.jw_a(p, n_qubits)
    adag_r = jw.jw_a_dagger(r, n_qubits)
    a_r = jw.jw_a(r, n_qubits)
    generator = adag_p @ a_r - adag_r @ a_p
    # generator is anti-Hermitian; expm of a small dense matrix
    return expm(theta * generator)


def givens_two_qubit_matrix(theta: float) -> np.ndarray:
    """4x4 Givens matrix for adjacent qubits (p, r) with p < r, no JW
    string in between.

    In the basis ``|b_r b_p>`` (qubit p as LSB, qubit r as MSB):
        |00> -> |00>
        |01> (e_p) -> cos |01> - sin |10>
        |10> (e_r) -> sin |01> + cos |10>
        |11> -> |11>
    """
    c = np.cos(theta)
    s = np.sin(theta)
    return np.array(
        [
            [1, 0, 0, 0],
            [0, c, s, 0],
            [0, -s, c, 0],
            [0, 0, 0, 1],
        ],
        dtype=complex,
    )


def givens_gate(theta: float, p: int, r: int, n_qubits: int) -> Gate:
    """Return a Gate that applies G_{pr}(theta) as a *full 2**n x 2**n
    dense matrix* on the n-qubit register. For small systems used by
    tests this is the cleanest way to respect JW strings when p and r
    are not adjacent.

    Note: the returned Gate has ``qubits = (0, 1, ..., n_qubits - 1)``
    and an ``n_qubits``-qubit matrix. For topology-hashing purposes we
    still label it with the logical pair ``(p, r)`` via ``kind``.
    """
    mat = givens_fermionic_matrix(theta, p, r, n_qubits)
    return Gate(
        name=f"Givens({p},{r},{theta:.4f})",
        qubits=tuple(range(n_qubits)),
        matrix=mat,
        kind=f"Givens({p},{r})",
    )
